[tool.portray]
include_reference_documentation = false

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."Getting Started"]]
    "Python" = "docs/python101.md"

    [[tool.portray.mkdocs.nav."Getting Started"]]
    "GitHub" = "docs/github101.md"

    [[tool.portray.mkdocs.nav."Getting Started"]]
    "MSI" = "docs/msi101.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."Best Practices"]]
    "RST Guidelines" = "docs/rst-guidelines.md"

    [[tool.portray.mkdocs.nav."Best Practices"]]
    "Articles" = "docs/best-practices/articles.md"